"""The conversation state machine: IDLE (wake-word listening) -> greet ->
ACTIVE (listen/transcribe/respond loop) -> stop phrase -> back to IDLE.

The greeting is spoken directly from the hardcoded GREETING/CLAP_GREETING
constants, never generated by the model -- an LLM asked to "say this
greeting" could paraphrase or drop punctuation, which isn't acceptable for
a phrase specified verbatim. Which one is spoken depends on which trigger
fired (WakeWordListener.wait() reports "wake_word" or "clap").
"""

from __future__ import annotations

import threading

from jarvis.assistant.llm_client import send_turn
from jarvis.config import CLAP_GREETING, GREETING, STOP_PHRASES

_GREETING_BY_TRIGGER = {"wake_word": GREETING, "clap": CLAP_GREETING}

GOODBYE = "Até logo, Senhor Nicholas."
MAX_CONSECUTIVE_EMPTY_TRANSCRIPTIONS = 3


def _is_stop_phrase(text: str) -> bool:
    normalized = text.strip().lower().rstrip(".!")
    return normalized in STOP_PHRASES


def run_text_loop() -> None:
    print(GREETING)
    messages: list[dict] = []
    while True:
        try:
            text = input("Você: ").strip()
        except EOFError:
            break
        if not text:
            continue
        if _is_stop_phrase(text):
            print(f"JARVIS: {GOODBYE}")
            break
        messages.append({"role": "user", "content": text})
        reply = send_turn(messages)
        print(f"JARVIS: {reply}")


def _run_active_session(listener, record_utterance, transcribe, speak) -> None:
    """One wake-word session's ACTIVE loop, with its dependencies passed in
    so it's testable without real audio/model/TTS. Always unloads the STT
    model on the way out -- whether the session ended via stop phrase or via
    the walk-away fallback below -- since this is the natural, instantaneous
    "session over" boundary: the model stays resident for the whole
    multi-turn conversation (no per-turn reload cost) and frees the moment
    it ends, no idle-timeout thread needed."""
    from jarvis.voice import stt

    messages: list[dict] = []
    consecutive_empty = 0
    try:
        while True:
            pcm = record_utterance(listener)
            text = transcribe(pcm)

            if not text:
                consecutive_empty += 1
                # The user may have walked away without saying a stop phrase --
                # without this, the loop would otherwise spin forever on empty
                # transcriptions and stt.unload() below would never run.
                if consecutive_empty >= MAX_CONSECUTIVE_EMPTY_TRANSCRIPTIONS:
                    speak(GOODBYE)
                    return
                continue
            consecutive_empty = 0

            if _is_stop_phrase(text):
                speak(GOODBYE)
                return

            messages.append({"role": "user", "content": text})
            reply = send_turn(messages)
            if reply:
                speak(reply)
    finally:
        stt.unload()


def run_voice_loop(stop_event: threading.Event | None = None) -> None:
    """Runs until an unhandled exception, or (when `stop_event` is given, as
    the menu-bar app does) until it's set -- checked between wake-word
    sessions, so "off" takes effect immediately while idle, or as soon as
    the current conversation naturally ends if one is in progress."""
    from jarvis.voice import audio, stt, tts
    from jarvis.voice.wake_word import WakeWordListener

    listener = WakeWordListener()
    try:
        while stop_event is None or not stop_event.is_set():
            trigger = listener.wait(stop_event=stop_event)
            if trigger is None:
                break
            tts.speak(_GREETING_BY_TRIGGER[trigger])
            _run_active_session(listener, audio.record_utterance, stt.transcribe, tts.speak)
    finally:
        listener.close()
