"""The conversation state machine: IDLE (wake-word listening) -> greet ->
ACTIVE (listen/transcribe/respond loop) -> stop phrase -> back to IDLE.

The greeting is spoken directly from the hardcoded GREETING/CLAP_GREETING
constants, never generated by the model -- an LLM asked to "say this
greeting" could paraphrase or drop punctuation, which isn't acceptable for
a phrase specified verbatim. Which one is spoken depends on which trigger
fired (WakeWordListener.wait() reports "wake_word" or "clap"). Right after
the greeting, a proactive briefing (jarvis/assistant/briefing.py) speaks up
only if there's something pending (a résumé proposal to review, an open
conflict) -- also code-derived, never the model's own words, same reasoning
as the greeting.

Each state transition (idle/listening; "speaking" fires from tts.speak()
itself, see jarvis/voice/tts.py) is published to jarvis/visualizer/state.py
-- purely a live visual aid (the menu bar's "Visualizar Interação" button),
never read back by anything here.
"""

from __future__ import annotations

import threading

from jarvis.assistant.llm_client import send_turn
from jarvis.config import CLAP_GREETING, GREETING, STOP_PHRASES

_GREETING_BY_TRIGGER = {"wake_word": GREETING, "clap": CLAP_GREETING}

GOODBYE = "Até logo, Senhor Nicholas."
MAX_CONSECUTIVE_EMPTY_TRANSCRIPTIONS = 3


def _is_stop_phrase(text: str) -> bool:
    normalized = text.strip().lower().rstrip(".!")
    return normalized in STOP_PHRASES


def run_text_loop() -> None:
    from jarvis.assistant.briefing import build_briefing

    print(GREETING)
    briefing = build_briefing()
    if briefing:
        print(f"JARVIS: {briefing}")
    messages: list[dict] = []
    while True:
        try:
            text = input("Você: ").strip()
        except EOFError:
            break
        if not text:
            continue
        if _is_stop_phrase(text):
            print(f"JARVIS: {GOODBYE}")
            break
        messages.append({"role": "user", "content": text})
        reply = send_turn(messages)
        print(f"JARVIS: {reply}")


def _run_active_session(
    listener, record_utterance, transcribe, speak, stop_event: threading.Event | None = None
) -> None:
    """One wake-word session's ACTIVE loop, with its dependencies passed in
    so it's testable without real audio/model/TTS. Always unloads the STT
    model on the way out -- whether the session ended via stop phrase or via
    the walk-away fallback below -- since this is the natural, instantaneous
    "session over" boundary: the model stays resident for the whole
    multi-turn conversation (no per-turn reload cost) and frees the moment
    it ends, no idle-timeout thread needed.

    `stop_event` is forwarded to every `speak()` call so "Desligar JARVIS"
    (the menu bar's off-toggle) interrupts speech that's already in
    progress instead of waiting for the current sentence to finish."""
    from jarvis.visualizer import state as visualizer_state
    from jarvis.voice import stt

    messages: list[dict] = []
    consecutive_empty = 0
    try:
        while True:
            visualizer_state.publish("listening")
            pcm = record_utterance(listener)
            text = transcribe(pcm)

            if not text:
                consecutive_empty += 1
                # The user may have walked away without saying a stop phrase --
                # without this, the loop would otherwise spin forever on empty
                # transcriptions and stt.unload() below would never run.
                if consecutive_empty >= MAX_CONSECUTIVE_EMPTY_TRANSCRIPTIONS:
                    speak(GOODBYE, stop_event=stop_event)
                    return
                continue
            consecutive_empty = 0

            if _is_stop_phrase(text):
                speak(GOODBYE, stop_event=stop_event)
                return

            messages.append({"role": "user", "content": text})
            reply = send_turn(messages)
            if reply:
                speak(reply, stop_event=stop_event)
    finally:
        stt.unload()


def run_voice_loop(stop_event: threading.Event | None = None) -> None:
    """Runs until an unhandled exception the microphone can't be recovered
    from, or (when `stop_event` is given, as the menu-bar app does) until
    it's set -- checked between wake-word sessions, so "off" takes effect
    immediately while idle, or as soon as the current conversation
    naturally ends if one is in progress. Speech already in progress is cut
    short right away too -- see `_run_active_session` and `tts.speak`.

    A single bad frame read (a real, observed failure: `pvrecorder` raising
    `OSError: Failed to read from device` after another process briefly
    grabbed the mic) used to kill this whole function silently -- the
    thread just died, the menu bar kept showing "on" forever after, and
    JARVIS simply stopped responding with no visible error short of
    digging through the log file. Any exception from one wake-word session
    now closes and rebuilds the listener and keeps going instead; only a
    genuinely broken microphone (the rebuild itself failing) actually ends
    the loop."""
    import sys
    import time

    from jarvis.assistant.briefing import build_briefing
    from jarvis.visualizer import state as visualizer_state
    from jarvis.voice import audio, stt, tts, xtts_client
    from jarvis.voice.wake_word import WakeWordListener

    # Starts the XTTS worker as a genuinely separate OS process (see
    # xtts_client.py / xtts_worker.py) -- NOT xtts_engine.preload_in_background()
    # in-process anymore. That in-process version made torchcodec dlopen
    # the Homebrew-installed FFmpeg's shared libraries into this same
    # process -- which already has faster-whisper's own bundled FFmpeg (via
    # PyAV) loaded -- and macOS's ObjC runtime logged a real class collision
    # (AVFFrameReceiver/AVFAudioReceiver defined in both), warning of
    # "spurious casting failures and mysterious crashes". Wake-word/clap
    # detection stopped firing entirely right after, with no exception or
    # error anywhere -- consistent with silently corrupted audio capture,
    # not a coincidence. Running the model in its own process means that
    # risk, if it recurs at all, can never touch PvRecorder here.
    xtts_client.ensure_worker_started()

    listener = WakeWordListener()
    try:
        while stop_event is None or not stop_event.is_set():
            visualizer_state.publish("idle")
            try:
                trigger = listener.wait(stop_event=stop_event)
                if trigger is None:
                    break
                tts.speak(_GREETING_BY_TRIGGER[trigger], stop_event=stop_event)
                briefing = build_briefing()
                if briefing:
                    tts.speak(briefing, stop_event=stop_event)
                _run_active_session(
                    listener, audio.record_utterance, stt.transcribe, tts.speak, stop_event=stop_event
                )
            except Exception as exc:
                print(f"[voice_loop] erro inesperado ({exc!r}) -- reiniciando o microfone", file=sys.stderr)
                try:
                    listener.close()
                except Exception:
                    pass
                time.sleep(1)  # avoids a tight crash-loop if the failure is persistent, not transient
                listener = WakeWordListener()  # lets a genuinely broken mic propagate and end the loop
    finally:
        try:
            listener.close()
        except Exception:
            pass
