"""Builds JARVIS.app -- a thin wrapper app bundle, NOT a frozen/bundled
standalone build. py2app/PyInstaller were deliberately not used: this
project's dependency tree (torch, playwright, PyObjC WebKit, ctranslate2)
is large and includes native extensions/dynamic loading that those
freezers can struggle with -- and there's no real benefit to freezing it
anyway, since this only ever needs to run on this one machine.

The bundle's executable just launches this project's own .venv -- same
"only works on this machine, with the project at this exact path"
reasoning as the LaunchAgent .plist already in this repo, and correct for
a personal, single-user tool (not something meant to be copied elsewhere
or handed to someone else).

Run once (`python scripts/build_app.py`); safe to rerun any time (e.g.
after regenerating the icon, or if the project ever moves) -- rebuilds
from scratch rather than patching in place.
"""

from __future__ import annotations

import plistlib
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ICON_SRC = PROJECT_ROOT / "jarvis" / "assets" / "AppIcon.icns"
APP_NAME = "JARVIS.app"

LAUNCHER_SCRIPT = f"""#!/bin/bash
# Generated by scripts/build_app.py -- do not edit directly, rerun that
# script instead. Launches JARVIS's menu-bar app using this project's own
# venv, wherever this .app happens to be (Applications, Desktop, ...).
cd "{PROJECT_ROOT}"
exec "{PROJECT_ROOT}/.venv/bin/python" -m jarvis menubar
"""

INFO_PLIST = {
    "CFBundleName": "JARVIS",
    "CFBundleDisplayName": "JARVIS",
    "CFBundleIdentifier": "com.nicholasbirochi.jarvis",
    "CFBundleVersion": "1.0",
    "CFBundleShortVersionString": "1.0",
    "CFBundleExecutable": "JARVIS",
    "CFBundleIconFile": "AppIcon",
    "CFBundlePackageType": "APPL",
    "CFBundleInfoDictionaryVersion": "6.0",
    # No Dock icon/Cmd-Tab -- belt-and-suspenders alongside the runtime
    # NSApplicationActivationPolicyAccessory call in jarvis/menubar.py
    # itself (this stops even a brief Dock-icon flash during launch).
    "LSUIElement": True,
    "LSMinimumSystemVersion": "13.0",
    "NSHighResolutionCapable": True,
}


def build(target_dir: Path) -> Path:
    app_path = target_dir / APP_NAME
    if app_path.exists():
        shutil.rmtree(app_path)

    contents = app_path / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    with open(contents / "Info.plist", "wb") as f:
        plistlib.dump(INFO_PLIST, f)

    launcher_path = macos / "JARVIS"
    launcher_path.write_text(LAUNCHER_SCRIPT, encoding="utf-8")
    launcher_path.chmod(0o755)

    if ICON_SRC.exists():
        shutil.copy(ICON_SRC, resources / "AppIcon.icns")
    else:
        print(
            f"aviso: {ICON_SRC} não existe -- rode scripts/generate_app_icon.py "
            "primeiro pra ter um ícone de verdade (o app funciona sem, só fica sem ícone).",
            file=sys.stderr,
        )

    return app_path


def main() -> None:
    target_dir = Path(sys.argv[1]).expanduser() if len(sys.argv) > 1 else Path("/Applications")
    try:
        app_path = build(target_dir)
    except PermissionError:
        target_dir = Path.home() / "Applications"
        target_dir.mkdir(parents=True, exist_ok=True)
        app_path = build(target_dir)
    print(f"JARVIS.app criado em: {app_path}")


if __name__ == "__main__":
    main()
